<a href="https://colab.research.google.com/github/rajanaids-hub/Machine-Learnig/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PYTHON PROGRAMMING FUNDAMENTALS - PART B


This Notebook will cover the following topics:    
- Numpy basics
- Built-in methods and functions
- Obtain shape, length and type of Numpy arrays
- Reshape
- Minimum and maximum and their indices
- Mathematical Operations
- Indexing and slicing
- Selection



# NUMPY BASICS
- NumPy is a Linear Algebra Library used for multidimensional arrays
- Installation: Use the command window, type: conda install numpy

In [ ]:
import numpy as np

In [ ]:
# One-dimensional array
my_list = [5, 3, 10]
my_list

[5, 3, 10]

In [ ]:
y = np.array(my_list)

In [ ]:
y

array([ 5,  3, 10])

In [ ]:
type(y)

numpy.ndarray

In [ ]:
# multi-dimensional (Matrix definition)
matrix = np.array([[1, 2], [3, 4]])

In [ ]:
matrix

array([[1, 2],
       [3, 4]])

# BUILT-IN METHODS AND FUNCTIONS

In [ ]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(10)
x

array([0.5198945 , 0.13523158, 0.80818111, 0.57538452, 0.97865453,
       0.1616179 , 0.57281699, 0.65615678, 0.13921355, 0.93660582])

In [ ]:
x = np.random.rand(10, 10)
x

array([[0.17817395, 0.63988169, 0.88277919, 0.10777868, 0.98206504,
        0.40782168, 0.3147519 , 0.43003754, 0.94908509, 0.83486963],
       [0.50097165, 0.33848248, 0.36723503, 0.65225839, 0.54392978,
        0.80422388, 0.65820596, 0.17780719, 0.20203814, 0.81666006],
       [0.81486466, 0.80583797, 0.78410765, 0.59233852, 0.29610225,
        0.58312751, 0.10756716, 0.80544849, 0.66958633, 0.25781669],
       [0.69616721, 0.63000843, 0.28604828, 0.22840607, 0.14164459,
        0.76355087, 0.26002987, 0.79125789, 0.57339879, 0.26039477],
       [0.40039557, 0.00571299, 0.29274983, 0.33332714, 0.36675349,
        0.30074536, 0.08254144, 0.8547037 , 0.03286686, 0.9635139 ],
       [0.294033  , 0.90071366, 0.41767185, 0.39772211, 0.3190698 ,
        0.81177481, 0.29690537, 0.81067946, 0.78109447, 0.38682304],
       [0.59436578, 0.30524001, 0.59341808, 0.522663  , 0.8014742 ,
        0.88089554, 0.63013005, 0.23503616, 0.64798294, 0.22428669],
       [0.19947911, 0.71689095, 0.7853152

In [ ]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([-1.82087733, -0.12573077, -0.57090726,  0.15969277,  1.8758043 ,
       -0.58312505,  0.53260584,  0.65496701,  1.94199226, -0.29034518])

In [ ]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

2

In [ ]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 100, 15)
x

array([60, 27, 15, 73, 28, 87, 60, 40, 35,  9, 74, 98, 33,  9, 20])

In [ ]:
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [ ]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Array of ones
x = np.ones(15)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [ ]:
x.shape

(15, 15)

In [ ]:
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# SHAPE, LENGTH AND TYPE OF NUMPY ARRAYS

In [ ]:
# get Length
len(y)

3

In [ ]:
# get shape
y.shape

(3,)

In [ ]:
matrix.shape

(2, 2)

In [ ]:
matrix.dtype

dtype('int32')

# RESHAPE

In [ ]:
y = np.array([3, 5, 7, 8])
y.reshape(2,2)

array([[3, 5],
       [7, 8]])

# MAX AND MIN VALUES AND THEIR INDEX

In [ ]:
y.max()

8

In [ ]:
y.min()

3

In [ ]:
# Obtain the index of the max value
y.argmax()

3

In [ ]:
# Obtain the index of the min value
y.argmin()

0

# MATHEMATICAL OPERATIONS

In [ ]:
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [ ]:
y = np.arange(1, 5)
z = x+y
z

array([2, 4, 6, 8])

In [ ]:
z = x**2
z

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
k = np.sqrt(z)
k

array([1., 2., 3., 4.])

In [ ]:
z = np.exp(y)
z

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# ELEMENTS SLICING AND INDEXING

In [ ]:
x = np.random.randint(1,10, 10)
x

array([3, 1, 2, 9, 3, 8, 8, 9, 6, 1])

In [ ]:
x[3]

9

In [ ]:
x[0:3]

array([3, 1, 2])

In [ ]:
# Broadcasting, altering several values in a numpy array at once
x[0:6] = 10
x

array([10, 10, 10, 10, 10, 10,  8,  9,  6,  1])

In [ ]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[4, 1, 6, 9, 5],
       [6, 9, 9, 4, 2],
       [4, 7, 5, 6, 3],
       [3, 7, 8, 7, 6],
       [1, 8, 6, 4, 3]])

In [ ]:
# Get a row from a mtrix
matrix[2]

array([4, 7, 5, 6, 3])

In [ ]:
# Get element
matrix[0][2]

6

In [ ]:
mini_matrix = matrix[:3]
mini_matrix

array([[4, 1, 6, 9, 5],
       [6, 9, 9, 4, 2],
       [4, 7, 5, 6, 3]])

In [ ]:
mini_matrix = matrix[2:]
mini_matrix

array([[4, 7, 5, 6, 3],
       [3, 7, 8, 7, 6],
       [1, 8, 6, 4, 3]])

In [ ]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[4, 1],
       [6, 9],
       [4, 7],
       [3, 7],
       [1, 8]])

In [ ]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[6, 9, 5],
       [9, 4, 2],
       [5, 6, 3],
       [8, 7, 6],
       [6, 4, 3]])

# ELEMENTS SELECTION

In [ ]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[6, 4, 9, 9, 2],
       [7, 6, 1, 9, 1],
       [1, 6, 1, 8, 2],
       [8, 6, 9, 8, 7],
       [7, 2, 8, 1, 8]])

In [ ]:
new_matrix = matrix[matrix>3]
new_matrix

array([6, 4, 9, 9, 7, 6, 9, 6, 8, 8, 6, 9, 8, 7, 7, 8, 8])

In [ ]:
new_matrix = matrix[matrix%2==0]
new_matrix

# NOW YOU HAVE MASTERED NUMPY, GIVE YOURSELF A PAT ON THE SHOULDER!